[package]
name = "kryp"
version = "0.0.0"
default-run = "kryp"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
rust_decimal = "1.29"
rust_decimal_macros = "1.29"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.28", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
tauri = { version = "2", features = [
	"devtools",
] }
chrono = { version = "0.4", features = ["serde"] }
csv = "1.2"
atomicwrites = "0.4"
lazy_static = "1.4"
chrono-tz = "0.8"
localzone = { version = "0.2", features = ["auto_validation"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
regex = "1.11.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
