[package]
name = "kryp"
version = "0.1.0"
description = "A Tauri App"
default-run = "kryp"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.5", features = [] }

[dependencies]
rust_decimal = "1.13.0"
rust_decimal_macros = "1.13.0"
reqwest = { version = "0.11.3", features = ["json"] }
tokio = { version = "1.6.0", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.0"
tauri = { version = "1.0.0-rc.6", features = ["dialog-open", "dialog-save", "shell-execute", "shell-open"] }
chrono = { version = "0.4.19", features = ["serde"] }
csv = "1.1.6"
atomicwrites = "0.3.0"
lazy_static = "1.4.0"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
