import router from '@/router/index.js'
import axios from 'axios'
const apiUrl = process.env.VUE_APP_API_URL
const xhr = {
  post: (slug, data) => {
    return axios.post(apiUrl + slug, data)
  },
}

const $pocket = {
  darkTheme: false,
  toggleDarkTheme () {
    this.darkTheme = !this.darkTheme
    this.updateTheme()
  },
  updateTheme () {
    const dataset = document.querySelector('html').dataset
    if (this.darkTheme === true) dataset.theme = 'dark'
    else dataset.theme = 'light'
  },
}

const $account = {
  loggedIn: false,
  email: null,
  firstName: null,
  lastName: null,
  login (redirectTo) {
    this.loggedIn = true
    this.email = 'example@gmail.com'
    this.firstName = 'Foo'
    this.lastName = 'Barson'
    if (redirectTo) router.push(redirectTo)
  },
  signup (data, redirectTo) {
    return new Promise((resolve, reject) => {
      xhr.post('/register', {
        email: data.email,
        password: data.password,
      }).then(() => {
        resolve()
      }).catch(err => {
        let customErr
        if (err.response) customErr = err.response.data
        else customErr = { msg: 'Server unreachable' }
        console.log('Error when signing up:')
        console.log(customErr)
        console.dir(err)
        reject(customErr)
      })
    })
  },
  logout (callback) {
    this.loggedIn = false
    this.email = null
    this.firstName = null
    this.lastName = null
    if (callback) callback()
  },
}

const $portfolios = {
  defaultId: '464fuh3na3',
  currentId: null,
  current: null,
  getCurrentFromRoute () {
    const currentId = router.currentRoute.params.portfolioId
    return this.portfolios.find(p => p.id === currentId)
  },
  setPortfolio (id) {
    this.currentId = id
    this.current = this.portfolios.find(p => p.id === id)
  },
  getIdFromName (name) {
    return this.portfolios.find(p => p.name === name).id
  },
  idExists (id) {
    return this.portfolios.some(p => p.id === id)
  },
  portfolios: [
    {
      id: '2n8pgyqnvq',
      name: 'Main',
    },
    {
      id: '464fuh3na3',
      name: 'Crypto',
      transactions: [
        {
          type: 'Trade',
          buy: '0.00000001',
          buyAsset: 'BTC',
          sell: '1.00000000',
          sellAsset: 'USD',
          fee: '0.01000000',
          feeAsset: 'USD',
          account: 'Binance',
          time: '2020-03-11 02:32:11',
        },
        {
          type: 'Deposit',
          buy: '0.00000001',
          buyAsset: 'BTC',
          sell: '',
          sellAsset: '',
          fee: '0.01000000',
          feeAsset: 'USD',
          account: 'Binance',
          time: '2019-08-21 11:23:46',
        },
        {
          type: 'External Buy',
          buy: '0.00000001',
          buyAsset: 'BTC',
          sell: '',
          sellAsset: '',
          fee: '0.01000000',
          feeAsset: 'USD',
          account: 'Binance',
          time: '2019-08-21 11:23:46',
        },
      ],
    },
    {
      id: '9ggukb7jtk',
      name: 'Stocks and stuff haha',
    },
  ],
  create (name) {
    this.portfolios.push({
      id: 'autogenerated',
      name: name,
    })
  },
}
$portfolios.setPortfolio($portfolios.defaultId)

export default {
  $pocket,
  $account,
  $portfolios,
}
