import router from '@/router/index.js'
import axios from 'axios'
let apiUrl
if (process.env.NODE_ENV === 'production') {
  apiUrl = process.env.VUE_APP_PRODUCTION_API_URL
} else {
  let protocol = 'http'
  let port = process.env.VUE_APP_API_HTTP_PORT
  if (location.protocol === 'https:') {
    protocol = 'https'
    port = process.env.VUE_APP_API_HTTPS_PORT
  }
  apiUrl = `${protocol}://${location.hostname}:${port}`
}

const xhr = {
  post: (slug, data = {}) => {
    let onSuccess
    if (typeof data.$onSuccess === 'function') onSuccess = data.$onSuccess
    if (onSuccess) delete data.$onSuccess
    return new Promise((resolve, reject) => {
      axios.post(apiUrl + slug, data, {
        withCredentials: true,
      }).then((response) => {
        if (onSuccess) onSuccess(response.data)
        resolve(response.data)
      }, (err) => {
        let customErr
        if (err.response) customErr = err.response.data
        else customErr = { msg: 'Server unreachable' }
        console.log(`Error sending POST request to ${slug}:`)
        console.log(customErr)
        console.dir(err)
        reject(customErr)
      })
    })
  },
}

const localS = {
  get: (name) => {
    return JSON.parse(localStorage.getItem(name))
  },
  set: (name, value) => {
    localStorage.setItem(name, JSON.stringify(value))
  },
}

const $pocket = {
  darkTheme: localS.get('darkTheme') || false,
  apiUrl: apiUrl,
  pageErrorMsg: '',
  setErrorMsg (value) {
    this.pageErrorMsg = value
  },
  clearErrorMsg () {
    this.pageErrorMsg = ''
  },
  toggleDarkTheme () {
    this.darkTheme = !this.darkTheme
    localS.set('darkTheme', this.darkTheme)
    this.updateTheme()
  },
  updateTheme () {
    const dataset = document.querySelector('html').dataset
    if (this.darkTheme === true) dataset.theme = 'dark'
    else dataset.theme = 'light'
  },
  loggedIn: false,
  email: null,
  init () {
    return xhr.post('/me', {
      $onSuccess: response => {
        this.loggedIn = true
        this.email = response.user.email
      },
    })
  },
  login (data) {
    return xhr.post('/login', {
      email: data.email,
      password: data.password,
      $onSuccess: response => {
        this.loggedIn = true
        this.email = response.user.email
      },
    })
  },
  signup (data, redirectTo) {
    return xhr.post('/register', {
      email: data.email,
      password: data.password,
    })
  },
  logout (callback) {
    return xhr.post('/logout', {
      $onSuccess: response => {
        this.loggedIn = false
        this.email = null
      },
    })
  },
  // portfolios
  defaultPortfolioId: '464fuh3na3',
  currentPortfolioId: null,
  current: null,
  getCurrentFromRoute () {
    return this.portfolios.find(p => p.id === router.currentRoute.params.portfolioId)
  },
  setPortfolio (id) {
    this.currentPortfolioId = id
    this.current = this.portfolios.find(p => p.id === id)
  },
  getIdFromName (name) {
    return this.portfolios.find(p => p.name === name).id
  },
  idExists (id) {
    return this.portfolios.some(p => p.id === id)
  },
  portfolios: [
    {
      id: '2n8pgyqnvq',
      name: 'Main',
    },
    {
      id: '464fuh3na3',
      name: 'Crypto',
      transactions: [
        {
          type: 'Trade',
          buy: '0.00000001',
          buyAsset: 'BTC',
          sell: '1.00000000',
          sellAsset: 'USD',
          fee: '0.01000000',
          feeAsset: 'USD',
          account: 'Binance',
          time: '2020-03-11 02:32:11',
        },
        {
          type: 'Deposit',
          buy: '0.00000001',
          buyAsset: 'BTC',
          sell: '',
          sellAsset: '',
          fee: '0.01000000',
          feeAsset: 'USD',
          account: 'Binance',
          time: '2019-08-21 11:23:46',
        },
        {
          type: 'External Buy',
          buy: '0.00000001',
          buyAsset: 'BTC',
          sell: '',
          sellAsset: '',
          fee: '0.01000000',
          feeAsset: 'USD',
          account: 'Binance',
          time: '2019-08-21 11:23:46',
        },
      ],
    },
    {
      id: '9ggukb7jtk',
      name: 'Stocks and stuff haha',
    },
  ],
  create (name) {
    this.portfolios.push({
      id: 'autogenerated',
      name: name,
    })
  },
}
$pocket.setPortfolio($pocket.defaultPortfolioId)

export default {
  $pocket,
}
