import axios from 'axios'
let apiUrl
if (process.env.NODE_ENV === 'production') {
  apiUrl = process.env.VUE_APP_PRODUCTION_API_URL
} else {
  let protocol = 'http'
  let port = process.env.VUE_APP_API_HTTP_PORT
  if (location.protocol === 'https:') {
    protocol = 'https'
    port = process.env.VUE_APP_API_HTTPS_PORT
  }
  apiUrl = `${protocol}://${location.hostname}:${port}`
}

const xhr = {
  post: (slug, data = {}) => {
    let onSuccess
    if (typeof data.$onSuccess === 'function') onSuccess = data.$onSuccess
    if (onSuccess) delete data.$onSuccess
    return new Promise((resolve, reject) => {
      axios.post(apiUrl + slug, data, {
        withCredentials: true,
      }).then((response) => {
        console.log(response.data)
        if (onSuccess) onSuccess(response.data)
        resolve(response.data)
      }, (err) => {
        let customErr
        if (err.response) customErr = err.response.data
        else customErr = { msg: 'Server unreachable' }
        console.log(`Error sending POST request to ${slug}:`)
        console.log(customErr)
        console.dir(err)
        reject(customErr)
      })
    })
  },
}

const localS = {
  get: (name) => {
    return JSON.parse(localStorage.getItem(name))
  },
  set: (name, value) => {
    localStorage.setItem(name, JSON.stringify(value))
  },
}

const $pocket = {
  loaded: false,
  darkTheme: localS.get('darkTheme') || false,
  apiUrl: apiUrl,
  pageErrorMsg: '',
  setErrorMsg (value) {
    this.pageErrorMsg = value
  },
  clearErrorMsg () {
    this.pageErrorMsg = ''
  },
  toggleDarkTheme () {
    this.darkTheme = !this.darkTheme
    localS.set('darkTheme', this.darkTheme)
    this.updateTheme()
  },
  updateTheme () {
    const dataset = document.querySelector('html').dataset
    if (this.darkTheme === true) dataset.theme = 'dark'
    else dataset.theme = 'light'
  },
  loggedIn: false,
  email: null,

  // account
  init () {
    return xhr.post('/me', {
      $onSuccess: response => {
        this.handleInitResponse(response)
      },
    })
  },
  login (data) {
    return xhr.post('/login', {
      email: data.email,
      password: data.password,
      $onSuccess: response => {
        this.handleInitResponse(response)
      },
    })
  },
  handleInitResponse (response) {
    this.portfolios = response.user.portfolios

    // set current portfolio
    if (!this.currentPortfolio) {
      const lastPortfolioId = localS.get('lastPortfolioId')
      const lastPortfolio = this.getPortfolio(lastPortfolioId)
      if (lastPortfolio) this.currentPortfolio = lastPortfolio
      else this.currentPortfolio = this.portfolios[0]
    }

    this.email = response.user.email
    this.loggedIn = true // must be last

    this.loaded = true
  },
  signup (data, redirectTo) {
    return xhr.post('/register', {
      email: data.email,
      password: data.password,
    })
  },
  logout (callback) {
    return xhr.post('/logout', {
      $onSuccess: response => {
        this.loggedIn = false
        this.email = null
      },
    })
  },

  // portfolios
  portfolios: [],
  currentPortfolio: null,
  getPortfolio (id) {
    return this.portfolios.find(p => p.id === id)
  },
  setPortfolioId (id) {
    this.currentPortfolio = this.getPortfolio(id)
  },
  createPortfolio (name) {
    this.portfolios.push({
      id: 'autogenerated',
      name: name,
    })
  },
}

window.$pocket = $pocket

export default {
  $pocket,
}
