
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async errorPopup(msg: string) : Promise<void> {
    await TAURI_INVOKE("error_popup", { msg });
},
async getSystemTimezone() : Promise<string | null> {
    return await TAURI_INVOKE("get_system_timezone");
},
async newFile(baseCurrency: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_file", { baseCurrency }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async open(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async save(saveAs: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save", { saveAs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns a hideApp bool
 */
async close() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isOpen() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_open") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTax() : Promise<Result<Tax, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tax") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTaxSettings() : Promise<Result<TaxSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tax_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTaxSettings(settings: TaxSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tax_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addTransaction(uncostedTx: UncostedTransaction) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_transaction", { uncostedTx }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHoldings() : Promise<Result<Holdings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_holdings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHoldingsValued() : Promise<Result<Holdings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_holdings_valued") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHoldingsByWallet() : Promise<Result<Partial<{ [key in string]: WalletHoldings }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_holdings_by_wallet") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAssets() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_assets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPrices(symbol: string) : Promise<Result<PriceDataAsset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_prices", { symbol }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDepositWithdrawalTags() : Promise<Result<DWTags, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_deposit_withdrawal_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getReport(year: number, deductibleTags: string[], incomeTags: string[], hideValuesLessThan: string, costBasisMethod: CostBasisMethod) : Promise<Result<Report, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_report", { year, deductibleTags, incomeTags, hideValuesLessThan, costBasisMethod }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadReport(year: number, deductibleTags: string[], incomeTags: string[], hideValuesLessThan: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_report", { year, deductibleTags, incomeTags, hideValuesLessThan }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns `true` if the scan was cancelled
 */
async scanImportFile(source: string, tz: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_import_file", { source, tz }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getImportData() : Promise<Result<ImportData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_import_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateImportTransactions(transactions: ImportTransaction[]) : Promise<Result<ImportData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_import_transactions", { transactions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async continueImport() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("continue_import") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelImport() : Promise<Result<null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_import") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async export() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTransactions(search: Search) : Promise<Result<Transaction[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transactions", { search }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
importStatus: ImportStatus,
openedEvent: OpenedEvent
}>({
importStatus: "import-status",
openedEvent: "opened-event"
})

/** user-defined constants **/



/** user-defined types **/

export type Api = { name: ApiName; key?: string | null; disabled: boolean }
export type ApiName = "ExchangerateHost" | "CoinGecko" | "CryptoCompare"
export type AssetKind = "Fiat" | "Crypto"
export type Balance = { acquire_date: number; amount: string; currency: string; wallet: string; cost: string }
export type CostBasisMethod = "fifo" | "hifo"
export type DWTags = { withdrawal_tags: string[]; deposit_tags: string[] }
export type Deposit = { tag: string; date: number; note: string; hash: string; amount: string; asset: string; wallet: string; manual_worth: string | null; 
/**
 * Includes fee
 */
cost: string }
export type Holding = { asset: string; amount: string; cost: string; value: string | null; error: string | null }
export type Holdings = { list: Holding[]; total_cost: string; total_value: string | null }
export type ImportData = { transactions: ImportTransaction[]; has_errors: boolean; source: string }
export type ImportStatus = { index: number; count: number }
export type ImportTransaction = { transaction: UncostedTransaction; cost: string | null; error: string | null }
export type Interval = "Daily" | "HourlyOrDaily"
export type OpenedEvent = { opened: boolean; file_path: string | null }
export type PriceData = { assets: Partial<{ [key in string]: PriceDataAsset }> }
export type PriceDataAsset = { name: string; symbol: string; id: string; kind: AssetKind; interval: Interval; prices: Partial<{ [key in number]: number }> }
export type Realized = { tag: string; date: number; input: string; asset: string; is_fee: boolean; output: string; wallet: string }
export type Report = { records: Row[]; total_deductible: string; total_income: string; total_realized_gain: string; total_realized_loss: string; total_realized: string }
export type Row = { name: string; income: string; deductible: string; realized_gain: string; realized_loss: string; realized: string }
export type Search = { tags: string[]; asset: string }
export type Tax = { version: string; transactions: Transaction[]; settings: TaxSettings; price_data: PriceData; realized_gains: Realized[]; balances: Balance[] }
export type TaxSettings = { cost_basis_method: CostBasisMethod; base_currency: string; apis: Api[] }
export type Trade = { tag: string; date: number; note: string; hash: string; sent_amount: string; sent_asset: string; sent_wallet: string; recv_amount: string; recv_asset: string; recv_wallet: string; fee_amount: string; fee_asset: string; manual_worth: string | null; 
/**
 * Includes fee
 */
cost: string }
/**
 * A transaction with a final cost set. This should not be directly created
 */
export type Transaction = ({ type: "Trade" } & Trade) | ({ type: "Transfer" } & Transfer) | ({ type: "Deposit" } & Deposit) | ({ type: "Withdrawal" } & Withdrawal)
export type Transfer = { tag: string; date: number; note: string; hash: string; sent_amount: string; sent_asset: string; sent_wallet: string; recv_amount: string; recv_asset: string; recv_wallet: string; manual_worth: string | null; 
/**
 * Includes fee
 */
cost: string }
/**
 * A transaction without a final cost set
 */
export type UncostedTransaction = ({ type: "Trade" } & Trade) | ({ type: "Transfer" } & Transfer) | ({ type: "Deposit" } & Deposit) | ({ type: "Withdrawal" } & Withdrawal)
export type WalletHoldings = { name: string; holdings: Holdings }
export type Withdrawal = { tag: string; date: number; note: string; hash: string; amount: string; asset: string; wallet: string; manual_worth: string | null; 
/**
 * Includes fee
 */
cost: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
