version: '3.4'
services:
  server:
    tty: true
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev-stage
    environment:
      SERVER_PORT: ${SERVER_PORT:?SERVER_PORT}
      DB_USERNAME: ${DB_USERNAME:?DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD}
      DB_PORT: ${DB_PORT:?DB_PORT}
    volumes:
      - ./server:/go/src/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
  db:
    tty: true
    container_name: db
    image: bitnami/mongodb:4.2
    environment:
      MONGODB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?DB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${DB_USERNAME:?DB_USERNAME}
      MONGODB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD}
      MONGODB_DATABASE: kryp
      MONGODB_EXTRA_FLAGS: --auth --port ${DB_PORT:?DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./mongodb:/bitnami/mongodb
