version: '3.4'
services:
  web:
    tty: true
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
      target: dev-stage
    environment:
      VUE_APP_API_URL: http://localhost:80
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - api
  api:
    tty: true
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run start-dev
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      API_SESSION_KEY: ${API_SESSION_KEY}
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
  db:
    tty: true
    container_name: db
    image: mongo:4.2-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: admin
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data/db
      - ./db/init-scripts/:/docker-entrypoint-initdb.d/
